### ISSUE TITLE
anyone knows how to render List data using Barber(0.3.3)?

### ISSUE THREAD

**Issue by dlutweibo** [cashapp/barber#115]
like mustache demo:

Template: 
{{#items}}
  {{#first}}
    `<li><strong>{{name}}</strong></li>`
  {{/first}}
  {{#link}}
    `<li><a href="{{url}}">{{name}}</a></li>`
  {{/link}}
{{/items}}

Input:
{
  "items": [
      {"name": "red", "first": true, "url": "#Red"},
      {"name": "green", "link": true, "url": "#Green"},
      {"name": "blue", "link": true, "url": "#Blue"}
  ]
}

output:
`<li><strong>red</strong></li>`
`<li><a href="#Green">green</a></li>`
`<li><a href="#Blue">blue</a></li>`

I used Set<MyDataClass> type, but there was a execption, like: 
"Failure to generate signature because of [memberProperty=properties] which must be a data class [returnType=kotlin.collections.Set<com.microsoft.thrifty.ogen.IDLModelHeaderProperty>]"

**Comment by adrw** [comment]
Thanks for reporting, we don't have rigorous testing or use of DocumentData schema's using non-String types. Barber has some initial support built in for supporting other Proto primitives like Instant and Duration but we haven't extended past that to other types like lists.

Though Barber uses Mustache under the hood, the Barber API and pattern exposed is a small, safer (ie. guardrails) subset of the power of Mustache.

**Comment by dlutweibo** [comment]
Thank you for the information
