### ISSUE TITLE
Misspelling in the website

### ISSUE THREAD

**Issue by LouisCAD** [cashapp/barber#95]
Hello, I spotted a typo on the main website page:

> Could the same unique data blob could be used to support templates in different languages?

I couldn't send a PR because of #94 

Have a great day!

Louis CAD

**Comment by adrw** [comment]
Thanks for reporting, what is the typo?

**Comment by LouisCAD** [comment]
There's an extra "could".

**Comment by LouisCAD** [comment]
Would you make the website open source so we can send PRs?
